<?php
declare(strict_types=1);
require dirname(__DIR__) . '/app/bootstrap.php';

$path = trim((string)parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH), '/');
$base = trim((string)parse_url($config['app_url'], PHP_URL_PATH), '/');
if ($base && str_starts_with($path, $base)) $path = trim(substr($path, strlen($base)), '/');
$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';

function rooms(): array { return db()->query('SELECT * FROM room_types WHERE active=1 ORDER BY base_price')->fetchAll(); }
function room_image(array $room): string { return url('assets/images/rarinco-real/' . ($room['image'] ?: 'room-matrimonial.webp')); }
function head_html(string $title, string $description): void { global $config; $canonical = url(trim((string)parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH), '/')); ?>
<!doctype html><html lang="es-CL"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?></title><meta name="description" content="<?=e($description)?>"><link rel="canonical" href="<?=e($canonical)?>"><meta property="og:type" content="website"><meta property="og:title" content="<?=e($title)?>"><meta property="og:description" content="<?=e($description)?>"><meta property="og:image" content="<?=url('assets/images/rarinco-real/room-matrimonial.webp')?>"><link rel="stylesheet" href="<?=url('assets/css/globals.css')?>"><link rel="stylesheet" href="<?=url('assets/css/public-refresh.css')?>"><link rel="stylesheet" href="<?=url('assets/css/php-app.css')?>"><script type="application/ld+json"><?=json_encode(['@context'=>'https://schema.org','@type'=>'Hotel','name'=>'Hotel Rarinco','url'=>$config['app_url'],'telephone'=>'+56978466768','address'=>['@type'=>'PostalAddress','streetAddress'=>'Avenida Las Industrias 2250','addressLocality'=>'Los Ángeles','addressRegion'=>'Biobío','addressCountry'=>'CL']], JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?></script></head><body>
<?php }
function brand(): void { ?><a class="brand" href="<?=url()?>"><img class="brand-logo" src="<?=url('assets/images/rarinco-real/logo-hotel-rarinco.webp')?>" alt=""><span><strong>Hotel Rarinco</strong><small>Los Ángeles · Biobío</small></span></a><?php }
function header_html(bool $home=false): void { ?><a class="skip-link" href="#contenido">Saltar al contenido</a><header class="site-header <?=$home?'':'inner-header'?>"><?php brand(); ?><nav class="nav" id="menu"><a href="<?=url()?>">Inicio</a><a href="<?=url('habitaciones')?>">Habitaciones</a><a href="<?=url('servicios')?>">Servicios</a><a href="<?=url('empresas')?>">Empresas</a><a href="<?=url('galeria')?>">Galería</a><a href="<?=url('contacto')?>">Contacto</a></nav><a class="header-book" href="<?=url('disponibilidad')?>">Reservar</a><button class="menu-button" type="button" aria-label="Abrir menú" onclick="document.getElementById('menu').classList.toggle('is-open')"><span></span><span></span></button></header><?php }
function footer_html(): void { ?><footer class="footer"><div class="footer-main"><div class="footer-brand"><?php brand(); ?><p>Una estadía cómoda y tranquila en Los Ángeles, con atención cercana para viajeros, familias y empresas.</p></div><div><h3>Hotel</h3><a href="<?=url('habitaciones')?>">Habitaciones</a><a href="<?=url('servicios')?>">Servicios</a><a href="<?=url('galeria')?>">Galería</a></div><div><h3>Reservas</h3><a href="<?=url('disponibilidad')?>">Buscar disponibilidad</a><a href="<?=url('mi-reserva')?>">Consultar reserva</a><a href="<?=url('preguntas-frecuentes')?>">Preguntas frecuentes</a></div><div><h3>Contacto</h3><p>Avenida Las Industrias 2250<br>Los Ángeles, Biobío</p><a href="tel:+56978466768">+56 9 7846 6768</a><a href="tel:+56984842842">+56 9 8484 2842</a></div></div><div class="footer-bottom"><span>© <?=date('Y')?> Hotel Rarinco</span><span><a href="<?=url('privacidad')?>">Privacidad</a><a href="<?=url('admin')?>">Administración</a></span></div></footer><a class="mobile-book" href="<?=url('disponibilidad')?>">Reservar</a></body></html><?php }
function page_start(string $title,string $intro=''): void { head_html($title.' | Hotel Rarinco',$intro ?: 'Hotel y alojamiento en Los Ángeles, Región del Biobío.'); header_html(); ?><main id="contenido"><section class="page-hero"><div><p class="eyebrow"><span></span>Hotel Rarinco</p><h1><?=e($title)?></h1><?php if($intro):?><p><?=e($intro)?></p><?php endif?></div></section><?php }
function page_end(): void { ?></main><?php footer_html(); }
function availability_form(): void { $in=$_GET['entrada']??date('Y-m-d',strtotime('+1 day')); $out=$_GET['salida']??date('Y-m-d',strtotime('+2 day')); ?><form class="availability" action="<?=url('disponibilidad')?>" method="get"><div class="form-title"><span>Reserva directa</span><strong>Encuentra tu habitación</strong></div><label>Entrada<input required name="entrada" type="date" min="<?=date('Y-m-d')?>" value="<?=e($in)?>"></label><label>Salida<input required name="salida" type="date" min="<?=date('Y-m-d',strtotime('+1 day'))?>" value="<?=e($out)?>"></label><label>Adultos<select name="adultos"><?php for($i=1;$i<=6;$i++):?><option><?=$i?></option><?php endfor?></select></label><label>Niños<select name="ninos"><?php for($i=0;$i<=4;$i++):?><option><?=$i?></option><?php endfor?></select></label><label>Habitaciones<select name="habitaciones"><?php for($i=1;$i<=4;$i++):?><option><?=$i?></option><?php endfor?></select></label><button>Buscar disponibilidad</button></form><?php }
function room_card(array $r,bool $available=false): void { ?><article class="room-card"><a class="room-image" href="<?=url('habitaciones/'.$r['slug'])?>"><img src="<?=room_image($r)?>" alt="<?=e($r['name'])?> en Hotel Rarinco" loading="lazy"></a><div class="room-card-body"><div class="room-meta"><span>Hasta <?=$r['capacity']?> huéspedes</span><span><?=e($r['beds'])?></span></div><h3><?=e($r['name'])?></h3><p><?=e($r['short_description'])?></p><div class="room-price"><span>Desde <strong><?=clp((int)$r['base_price'])?></strong> / noche</span><a href="<?=url(($available?'reservar':'habitaciones/'.$r['slug']).($available?'?tipo='.$r['id'].'&'.http_build_query($_GET):''))?>"><?=$available?'Elegir':'Ver habitación'?> →</a></div></div></article><?php }

if ($method==='POST') {
    verify_csrf();
    if ($path==='contacto') {
        $q=db()->prepare('INSERT INTO contact_messages(name,email,phone,subject,message) VALUES(?,?,?,?,?)');
        $q->execute([trim($_POST['name']),trim($_POST['email']),trim($_POST['phone']??''),trim($_POST['subject']),trim($_POST['message'])]); flash('success','Mensaje enviado. Nos comunicaremos contigo.'); redirect('contacto');
    }
    if ($path==='empresas') {
        $q=db()->prepare('INSERT INTO corporate_requests(company,rut,contact_name,email,phone,guests,start_date,end_date,requirements) VALUES(?,?,?,?,?,?,?,?,?)');
        $q->execute(array_map('trim',[$_POST['company'],$_POST['rut']??'',$_POST['contact_name'],$_POST['email'],$_POST['phone'],$_POST['guests'],$_POST['start_date'],$_POST['end_date'],$_POST['requirements']??''])); flash('success','Solicitud recibida. Prepararemos una cotización.'); redirect('empresas');
    }
    if ($path==='reservar') {
        $pdo=db(); $pdo->beginTransaction();
        try { $in=$_POST['check_in'];$out=$_POST['check_out'];$n=nights($in,$out); if($n<1) throw new RuntimeException('Fechas inválidas.');
            $q=$pdo->prepare('SELECT * FROM room_types WHERE id=? AND active=1');$q->execute([(int)$_POST['room_type_id']]);$type=$q->fetch(); if(!$type) throw new RuntimeException('Habitación inválida.');
            $available=$pdo->prepare("SELECT r.id FROM rooms r WHERE r.room_type_id=? AND r.status='available' AND NOT EXISTS(SELECT 1 FROM room_nights rn WHERE rn.room_id=r.id AND rn.stay_date>=? AND rn.stay_date<?) LIMIT 1");$available->execute([$type['id'],$in,$out]);$roomId=$available->fetchColumn(); if(!$roomId) throw new RuntimeException('No existe disponibilidad para esas fechas.');
            $g=$pdo->prepare('INSERT INTO guests(first_name,last_name,document,email,phone,city) VALUES(?,?,?,?,?,?)');$g->execute([trim($_POST['first_name']),trim($_POST['last_name']),trim($_POST['document']??''),trim($_POST['email']),trim($_POST['phone']),trim($_POST['city']??'')]);
            $code='HR-'.date('Y').'-'.strtoupper(substr(bin2hex(random_bytes(4)),0,6));$total=(int)$type['base_price']*$n;
            $r=$pdo->prepare("INSERT INTO reservations(code,guest_id,check_in,check_out,adults,children,rooms_count,nights,total,status,payment_method,special_requests) VALUES(?,?,?,?,?,?,?,?,?,'pending_review',?,?)");$r->execute([$code,$pdo->lastInsertId(),$in,$out,(int)$_POST['adults'],(int)($_POST['children']??0),1,$n,$total,$_POST['payment_method']??'transfer',trim($_POST['special_requests']??'')]);$reservationId=(int)$pdo->lastInsertId();
            $rr=$pdo->prepare('INSERT INTO reservation_rooms(reservation_id,room_id,nightly_price) VALUES(?,?,?)');$rr->execute([$reservationId,$roomId,$type['base_price']]);$rn=$pdo->prepare('INSERT INTO room_nights(reservation_id,room_id,stay_date) VALUES(?,?,?)');$d=new DateTime($in);$end=new DateTime($out);while($d<$end){$rn->execute([$reservationId,$roomId,$d->format('Y-m-d')]);$d->modify('+1 day');}$pdo->commit(); flash('success',"Reserva creada. Tu código es $code. Total: ".clp($total)); redirect('mi-reserva?code='.$code);
        } catch(Throwable $e){$pdo->rollBack();flash('error',$e->getMessage());redirect('disponibilidad');}
    }
    if ($path==='admin/login') { $q=db()->prepare('SELECT * FROM users WHERE email=? AND active=1');$q->execute([trim($_POST['email'])]);$u=$q->fetch();if($u&&password_verify($_POST['password'],$u['password_hash'])){session_regenerate_id(true);$_SESSION['admin_id']=$u['id'];redirect('admin');}flash('error','Credenciales incorrectas.');redirect('admin/login'); }
    if ($path==='admin/reserva') { require_admin(); $q=db()->prepare('UPDATE reservations SET status=? WHERE id=?');$q->execute([$_POST['status'],(int)$_POST['id']]);flash('success','Reserva actualizada.');redirect('admin'); }
}

if ($path==='admin/logout'){session_destroy();redirect('admin/login');}
if ($path==='admin/login'){head_html('Acceso administrativo','Panel de Hotel Rarinco');$f=pull_flash();?><main class="admin-login"><h1>Administración</h1><?php if($f):?><div class="status error"><?=e($f['message'])?></div><?php endif?><form method="post"><input type="hidden" name="_token" value="<?=csrf()?>"><label>Correo<input type="email" name="email" required></label><label>Contraseña<input type="password" name="password" required></label><button class="button blue full">Ingresar</button></form></main></body></html><?php exit;}
if (str_starts_with($path,'admin')){require_admin();head_html('Panel administrativo','Gestión Hotel Rarinco');$f=pull_flash();$rs=db()->query('SELECT r.*,g.first_name,g.last_name,g.email FROM reservations r JOIN guests g ON g.id=r.guest_id ORDER BY r.created_at DESC LIMIT 100')->fetchAll();?><main class="admin-shell"><div class="room-actions"><h1>Reservas</h1><a href="<?=url('admin/logout')?>">Cerrar sesión</a></div><?php if($f):?><div class="status"><?=e($f['message'])?></div><?php endif?><div class="admin-nav"><a href="<?=url('admin')?>">Reservas</a><a href="<?=url('admin?view=contactos')?>">Contactos</a><a href="<?=url('admin?view=empresas')?>">Empresas</a><a href="<?=url()?>">Ver sitio</a></div><table class="data-table"><thead><tr><th>Código</th><th>Huésped</th><th>Fechas</th><th>Total</th><th>Estado</th><th>Acción</th></tr></thead><tbody><?php foreach($rs as $r):?><tr><td><?=e($r['code'])?></td><td><?=e($r['first_name'].' '.$r['last_name'])?><br><small><?=e($r['email'])?></small></td><td><?=e($r['check_in'])?> → <?=e($r['check_out'])?></td><td><?=clp((int)$r['total'])?></td><td><span class="badge"><?=e($r['status'])?></span></td><td><form method="post" action="<?=url('admin/reserva')?>"><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="id" value="<?=$r['id']?>"><select name="status"><option>pending_review</option><option>confirmed</option><option>cancelled</option><option>checked_in</option><option>checked_out</option></select><button>Guardar</button></form></td></tr><?php endforeach?></tbody></table></main></body></html><?php exit;}

if ($path==='' || $path==='inicio') { head_html('Hotel en Los Ángeles, Chile | Hotel Rarinco','Alojamiento cómodo en Los Ángeles, Biobío, con desayuno, estacionamiento y reserva directa.');header_html(true);$rs=array_slice(rooms(),0,3);?><main id="contenido"><section class="hero"><div class="hero-shade"></div><div class="hero-content"><p class="eyebrow"><span></span>Hotel en Los Ángeles · Chile</p><h1>Tu pausa en el corazón del Biobío</h1><p class="hero-copy">Una estadía cómoda y cercana para descansar, trabajar o comenzar tus vacaciones en el sur de Chile.</p><div class="booking-assurance">Reserva directa · Tarifas en CLP · Confirmación del hotel</div></div><div class="hero-gallery"><figure class="hero-photo-main"><img src="<?=url('assets/images/rarinco-real/room-matrimonial.webp')?>" alt="Habitación Hotel Rarinco"></figure><figure class="hero-photo-small"><img src="<?=url('assets/images/rarinco-real/workspace.webp')?>" alt="Espacio de trabajo"></figure></div><?php availability_form();?></section><section class="benefit-strip"><div><span>01</span><strong>Desayuno incluido</strong></div><div><span>02</span><strong>Estacionamiento privado</strong></div><div><span>03</span><strong>Wi-Fi sin costo</strong></div><div><span>04</span><strong>Aire acondicionado</strong></div><div><span>05</span><strong>Atención permanente</strong></div></section><section class="intro-section"><div><p class="eyebrow dark"><span></span>Hotel Rarinco</p><h2>Una estadía pensada para descansar</h2></div><p>Espacios cómodos, atención cercana y servicios prácticos para una estadía tranquila en Los Ángeles, por trabajo, vacaciones o una pausa en la Ruta 5 Sur.</p></section><section class="section rooms-section"><div class="section-head"><div><p class="eyebrow dark"><span></span>Habitaciones</p><h2>El espacio que necesitas</h2></div><a class="outline-link" href="<?=url('habitaciones')?>">Ver todas</a></div><div class="room-grid"><?php foreach($rs as $r)room_card($r);?></div></section><section class="parallax-break"><div><p class="eyebrow"><span></span>Hospitalidad en Los Ángeles</p><h2>Una pausa serena en tu recorrido por el Biobío</h2><p>Habitaciones cómodas, servicios esenciales y atención cercana.</p></div></section><section class="event-feature section"><div><p class="eyebrow dark"><span></span>Viajes de trabajo</p><h2>Un espacio cómodo para descansar y avanzar</h2><p>Climatización, Wi-Fi y áreas de trabajo para quienes visitan Los Ángeles.</p><a class="button blue" href="<?=url('empresas')?>">Consultar convenios</a></div><img src="<?=url('assets/images/rarinco-real/workspace.webp')?>" alt="Espacio de trabajo"></section></main><?php footer_html();exit;}

if($path==='habitaciones'){page_start('Habitaciones para cada forma de viajar','Alternativas cómodas para viajes individuales, parejas, familias y empresas.');?><section class="section"><div class="room-grid"><?php foreach(rooms() as $r)room_card($r);?></div></section><?php page_end();exit;}
if(preg_match('#^habitaciones/([a-z0-9-]+)$#',$path,$m)){ $q=db()->prepare('SELECT * FROM room_types WHERE slug=? AND active=1');$q->execute([$m[1]]);$r=$q->fetch();if(!$r){http_response_code(404);$path='404';}else{page_start($r['name'],$r['short_description']);?><section class="section room-detail"><div class="detail-gallery"><img src="<?=room_image($r)?>" alt="<?=e($r['name'])?>"></div><aside><p class="eyebrow dark"><span></span>Desde <?=clp((int)$r['base_price'])?> / noche</p><h2>Comodidad para <?=$r['capacity']?> huéspedes</h2><p><?=e($r['description'])?></p><dl><div><dt>Camas</dt><dd><?=e($r['beds'])?></dd></div><div><dt>Horario</dt><dd>Entrada 15:00 · Salida 11:00</dd></div></dl><a class="button blue full" href="<?=url('disponibilidad')?>">Reservar</a></aside></section><?php page_end();exit;}}
if($path==='disponibilidad'){page_start('Disponibilidad y tarifas','Consulta habitaciones disponibles y continúa tu reserva.');$in=$_GET['entrada']??date('Y-m-d',strtotime('+1 day'));$out=$_GET['salida']??date('Y-m-d',strtotime('+2 day'));?><section class="section"><?php availability_form();?><div class="room-grid"><?php if(nights($in,$out)>0){$q=db()->prepare("SELECT rt.*,COUNT(r.id) inventory FROM room_types rt JOIN rooms r ON r.room_type_id=rt.id AND r.status='available' WHERE rt.active=1 AND NOT EXISTS(SELECT 1 FROM room_nights rn WHERE rn.room_id=r.id AND rn.stay_date>=? AND rn.stay_date<?) GROUP BY rt.id");$q->execute([$in,$out]);foreach($q->fetchAll() as $r)room_card($r,true);}?></div></section><?php page_end();exit;}
if($path==='reservar'){ $q=db()->prepare('SELECT * FROM room_types WHERE id=?');$q->execute([(int)($_GET['tipo']??0)]);$r=$q->fetch();page_start('Completa tu reserva','Reserva directa, segura y sujeta a confirmación del hotel.');$f=pull_flash();?><section class="section"><div class="reservation-box"><?php if($f):?><div class="status error"><?=e($f['message'])?></div><?php endif;if(!$r):?><p>Selecciona primero una habitación disponible.</p><?php else:?><h2><?=e($r['name'])?> · <?=clp((int)$r['base_price'])?> por noche</h2><form class="form-grid" method="post"><input type="hidden" name="_token" value="<?=csrf()?>"><input type="hidden" name="room_type_id" value="<?=$r['id']?>"><label>Entrada<input type="date" name="check_in" value="<?=e($_GET['entrada']??'')?>" required></label><label>Salida<input type="date" name="check_out" value="<?=e($_GET['salida']??'')?>" required></label><label>Nombre<input name="first_name" required></label><label>Apellidos<input name="last_name" required></label><label>Correo<input type="email" name="email" required></label><label>Teléfono<input name="phone" required></label><label>RUT o pasaporte<input name="document"></label><label>Ciudad<input name="city"></label><label>Adultos<input type="number" min="1" name="adults" value="<?=e($_GET['adultos']??'2')?>" required></label><label>Niños<input type="number" min="0" name="children" value="<?=e($_GET['ninos']??'0')?>"></label><label>Pago<select name="payment_method"><option value="transfer">Transferencia bancaria</option><option value="hotel">Pago en el hotel</option></select></label><label class="full">Solicitudes especiales<textarea name="special_requests"></textarea></label><button class="button blue full">Crear reserva</button></form><?php endif?></div></section><?php page_end();exit;}
if($path==='mi-reserva'){page_start('Consulta tu reserva','Revisa el estado usando tu código de reserva.');$f=pull_flash();$r=null;if(!empty($_GET['code'])){$q=db()->prepare('SELECT r.*,g.first_name,g.last_name,g.email FROM reservations r JOIN guests g ON g.id=r.guest_id WHERE r.code=?');$q->execute([strtoupper(trim($_GET['code']))]);$r=$q->fetch();}?><section class="section"><div class="reservation-box"><?php if($f):?><div class="status"><?=e($f['message'])?></div><?php endif?><form class="form-grid" method="get"><label class="full">Código<input name="code" value="<?=e($_GET['code']??'')?>" required></label><button class="button blue">Consultar</button></form><?php if($r):?><h2><?=e($r['code'])?></h2><p><strong>Huésped:</strong> <?=e($r['first_name'].' '.$r['last_name'])?></p><p><strong>Fechas:</strong> <?=e($r['check_in'])?> al <?=e($r['check_out'])?></p><p><strong>Total:</strong> <?=clp((int)$r['total'])?></p><p><strong>Estado:</strong> <span class="badge"><?=e($r['status'])?></span></p><?php endif?></div></section><?php page_end();exit;}
if($path==='servicios'){page_start('Servicios para una estadía más simple','Comodidades esenciales para descansar, trabajar y continuar tu viaje.');$services=[['☕','Desayuno incluido'],['P','Estacionamiento privado'],['⌁','Wi-Fi gratuito'],['❄','Climatización'],['24','Atención permanente'],['▦','Sala de reuniones'],['⌂','Habitaciones familiares'],['◇','Convenios para empresas']];?><section class="section simple-grid"><?php foreach($services as $s):?><article><i class="service-icon"><?=$s[0]?></i><h2><?=$s[1]?></h2><p>Servicio disponible para hacer tu estadía más cómoda y tranquila.</p></article><?php endforeach?></section><?php page_end();exit;}
if($path==='galeria'){page_start('Galería del hotel','Conoce nuestras habitaciones y espacios.');?><section class="gallery-strip"><?php foreach(['room-matrimonial.webp','workspace.webp','room-triple.webp','room-family.webp','room-double-work.webp'] as $img):?><img src="<?=url('assets/images/rarinco-real/'.$img)?>" alt="Hotel Rarinco Los Ángeles" loading="lazy"><?php endforeach?></section><?php page_end();exit;}
if($path==='contacto'){page_start('Contacto y ubicación','Escríbenos para resolver tus dudas sobre alojamiento en Los Ángeles.');$f=pull_flash();?><section class="section"><div class="reservation-box"><?php if($f):?><div class="status"><?=e($f['message'])?></div><?php endif?><form class="form-grid" method="post"><input type="hidden" name="_token" value="<?=csrf()?>"><label>Nombre<input name="name" required></label><label>Correo<input type="email" name="email" required></label><label>Teléfono<input name="phone"></label><label>Asunto<input name="subject" required></label><label class="full">Mensaje<textarea name="message" required></textarea></label><button class="button blue">Enviar mensaje</button></form></div></section><?php page_end();exit;}
if($path==='empresas'){page_start('Estadías para empresas','Cotizaciones para equipos, trabajadores y estadías prolongadas en Los Ángeles.');$f=pull_flash();?><section class="section"><div class="reservation-box"><?php if($f):?><div class="status"><?=e($f['message'])?></div><?php endif?><form class="form-grid" method="post"><input type="hidden" name="_token" value="<?=csrf()?>"><label>Empresa<input name="company" required></label><label>RUT<input name="rut"></label><label>Contacto<input name="contact_name" required></label><label>Correo<input type="email" name="email" required></label><label>Teléfono<input name="phone" required></label><label>Huéspedes<input type="number" min="1" name="guests" required></label><label>Entrada<input type="date" name="start_date" required></label><label>Salida<input type="date" name="end_date" required></label><label class="full">Requerimientos<textarea name="requirements"></textarea></label><button class="button blue">Solicitar cotización</button></form></div></section><?php page_end();exit;}

http_response_code(404);page_start('Página no encontrada','El contenido solicitado no está disponible.');?><section class="section"><a class="button blue" href="<?=url()?>">Volver al inicio</a></section><?php page_end();
